# Generated by Django 5.1.1 on 2024-10-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='agv_id',
        ),
    ]
