# Generated by Django 5.1.1 on 2024-10-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_data', '0002_rename_id_order_order_id_remove_order_agv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='load_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='load_weight',
            field=models.IntegerField(default=0),
        ),
    ]
