# Generated by Django 5.1.1 on 2024-11-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_data', '0003_order_load_amount_alter_order_load_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
