# Generated by Django 5.1.1 on 2024-10-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agv_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('load_name', models.CharField(max_length=100)),
                ('load_amount', models.IntegerField()),
            ],
        ),
    ]
