# Generated by Django 5.1.1 on 2024-10-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_draft', '0003_alter_orderdraft_end_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdraft',
            name='end_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdraft',
            name='start_point',
            field=models.IntegerField(),
        ),
    ]
