# Generated by Django 5.1.1 on 2024-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_draft', '0004_alter_orderdraft_end_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdraft',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
