# Generated by Django 5.1.1 on 2024-10-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_draft', '0005_alter_orderdraft_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdraft',
            name='order_date',
            field=models.DateField(),
        ),
    ]
