# Generated by Django 5.1.1 on 2024-10-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agv_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('start_point', models.IntegerField()),
                ('end_point', models.IntegerField()),
                ('load_name', models.CharField(max_length=100)),
                ('load_amount', models.IntegerField()),
            ],
        ),
    ]
